### ISSUE TITLE
Can plug-in auto update interlink when rename the note? 

### ISSUE THREAD

**Issue by chumido98** [SkepticMystic/breadcrumbs#110]
Can plug-in auto update interlink when rename the note?

**Comment by SkepticMystic** [comment]
Not if the link is in the yaml.

But if you use Dataview inline fields, Obsidian will automatically rename the link because it's just a regular link.

**Comment by chumido98** [comment]
> Not if the link is in the yaml.
> 
> But if you use Dataview inline fields, Obsidian will automatically rename the link because it's just a regular link.

Can you guide me how to do that? I'm new.

**Comment by SkepticMystic** [comment]
Welcome :)
Dataview is a different plugin you can use with Obsidian. It is a very powerful tool. One of its features let's you add metadata field in the **content** of your note, not the yaml like Obsidian limits you to.
So if you install Dataview and enable it, you can now put `parent:: [[Note]]` in the content of your note (see the double colons for inline fields `::`).
Because it's in the content of your note, the link will be renamed if you change it.

Let me know if that helps.

**Comment by chumido98** [comment]
![CleanShot 2021-08-25 at 13 25 01@2x](https://user-images.githubusercontent.com/61721378/130737580-300ad071-0b9c-41ab-aaf0-9e23e40d117c.png)
![CleanShot 2021-08-25 at 13 25 12@2x](https://user-images.githubusercontent.com/61721378/130737582-17a7d058-08e0-42f6-9872-7c75a1339919.png)

Like this or i missed somethings?

**Comment by SkepticMystic** [comment]
@chumido98 exactly like that, yes! You see how Breadcrumbs can detect those links, in the right side Matrix view.
So now, if you rename `002 dad` to something else, the link `parent:: [[002 dad]]` will also get updated.

**Comment by chumido98** [comment]
> @chumido98 exactly like that, yes! You see how Breadcrumbs can detect those links, in the right side Matrix view.
> So now, if you rename `002 dad` to something else, the link `parent:: [[002 dad]]` will also get updated.

 I greatly appreciate your help. Besttt.
