### ISSUE TITLE
Link to csv

### ISSUE THREAD

**Issue by iris2jane** [SkepticMystic/breadcrumbs#141]
Thanks for this great work. However, I want to avoid creating too many markdown files during use. Can direct connection to CSV be supported? As shown in the figure below, (I'm not sure about the feasibility of this idea😂)
![Drawing 2021-10-08 20 12 46 excalidraw](https://user-images.githubusercontent.com/36763930/136561472-5f0b9613-d1fa-4ab2-83f5-67f5b2fa0a47.png)

**Comment by SkepticMystic** [comment]
Ohhhh interesting! Haha this would work really well with my [metadataframe](https://github.com/SkepticMystic/metadataframe) plugin!
I'll give it a try, I don't think it should be too difficult, actually.
I'll make it so that you supply a file path to a csv in your vault, then I read that file and add any links to the Breadcrumbs graph.
I will use the existing hierarchies you have set up to grab the `↑, →, ↓` fileds from the csv

| file | parent |
| - | - |
| note.md | parentNote.md |

**Comment by SkepticMystic** [comment]
@iris2jane can you test this out in 0.10.73 😄 
It's kinda delicate for now. 
- You give it the path to a csv file in your vault, then it adds those crumbs to the hierarchy (the setting is found under `Settings > General Options`).
- You have to have a column called `file` with the note name in it (not the path, and don't add `.md`)
- Then each other column must be a filed name from your hierarchies.

This file is a working example:
```csv
file, up
test, testP
1, 2
another, parent
```

**Comment by jakeoung** [comment]
Any news for this feature!?

**Comment by SkepticMystic** [comment]
@jakeoung @iris2jane if you are willing, I think I've fixed this feature in the latest beta release found [here](https://github.com/SkepticMystic/breadcrumbs/releases/tag/1.3.1). You will have to manually install it, and it is **entirely possible** you experience some other bug due to the large number of changes that have occurred elsewhere.
Let me know if you need help setting it up, otherwise I'm keen to hear if this works :)

**Comment by SkepticMystic** [comment]
Update: The beta release I mentioned has been merged into main, so it is now fully available on the plugin list :)

**Comment by jakeoung** [comment]
Thank you so much! It works smoothly. I actually use md file instead of csv file, so that I can edit in obsidian. I'm sorry to ask for again lol, but could you consider supporting filenames with [[ ]] ?

For example, it also supports something like:
```
file, up
[[test]], [[testP]]
```

In implementation, maybe we can just remove [[ or ]] characters. The reason I ask for is that when I change the note title, it will automatically reflect the change (when my file is a md file). I would very appreciate if you could support it!!

**Comment by SkepticMystic** [comment]
@jakeoung glad it's working!
Could you please add a separate FR for that :)
