### ISSUE TITLE
Update links when filenames change

### ISSUE THREAD

**Issue by retospect** [SkepticMystic/breadcrumbs#174]
If I have 

[parent.md]
something

[child.md]
up: [ [[parent]] ]

and then rename parent.md to foo.md, the child's reference is not automatically updated and the breadcrum tree is broken.

Part of the value of Obsidian is to be able to rename things and retain link integrity, it would be awesome if the references would also be updated on rename.

**Comment by SkepticMystic** [comment]
I get you.
This happens because Obsidian doesn't see `up: [ [[parent]] ]` as an actual link.
Theoretically, I could add support for your request. However, there are so many different syntaxes that Breadcrumbs recognises that making this feature would be a plugin in itself.
My recommendation for now is:
1. Use Dataview inline fields: https://github.com/blacksmithgu/obsidian-dataview#data
2. Use this syntax if you want to keep using YAML `parent: ["note"]`, as Licat is going to add support for links in YAML in the future
