### ISSUE TITLE
Bug: Refresh Breadcrumbs Index on load

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#182]
I noticed that after restarting Obsidian, I have to reload the Breadcrumb Index. I assume this is a bug, since refreshing the index on load was probably a feature?

<img width="448" alt="Screenshot 2021-11-30 11 41 39" src="https://user-images.githubusercontent.com/73286100/144032773-7d95c5ac-fae4-4224-83d3-9b7251ce0605.png">

**Comment by SkepticMystic** [comment]
The index does try to refresh on start, yes.
This bug has been here since the start. It's because BC tries to load before Dataview is finished indexing. I've tried soooo many different ways around this. Even the official dataview API's event for when the index is ready. But nothing. I keep trying every now and then, but it's a pesky one

**Comment by chrisgrieser** [comment]
Oh, I didn't know. Does this only occur due to dataview, like is there a dataview setting one can change to avoid this?

**Comment by HEmile** [comment]
I'm also getting this bug, but I don't have DV installed.

**Comment by SkepticMystic** [comment]
I think the same thing happens waiting for the Obsidian metadataCache

**Comment by SkepticMystic** [comment]
I have made this more stable. It's possible the issue persists on much larger vaults, but no notices should appear for this

**Comment by chrisgrieser** [comment]
btw, I managed to make Breadcrumbs refresh on load by using the [JavaScript](obsidian://show-plugin?id=obsidian-javascript-init) init plugin and simply adding the refresh command there:

```js
app.plugins.plugins['breadcrumbs'].refreshIndex()
```
