### ISSUE TITLE
BC-folder-note: Option for subfolders

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#218]
I am trying to use a central note in a folder as parent for other files in that folder and it works great, however it seems that notes in *subfolders* are not supported. 

How about an option to have `BC-folder-note` also include notes that are located in subfolders of the same folder?

**Comment by SkepticMystic** [comment]
Ooooohh interesting! Yeah, I like this idea.
I think the easiest is what you suggest. Even notes in subfolders are just made the child of the `BC-folder-note`.
A fancier option would be a nested thing where subfolders have their own folder-note that they point to, as _those_ folder notes point to the main ones

**Comment by WychWitch** [comment]
I had JUST encountered this issue! I also would love this ^^

**Comment by SkepticMystic** [comment]
@WychWitch @chrisgrieser in the latest version, you can add `BC-folder-note-subfolder: true` to a folderNote to have the notes in _subfolders_ of that folder note get added, too :)
Let me know if this is what you meant

**Comment by chrisgrieser** [comment]
it works fine 🥳 

But I was actually thinking targeting things *only* in a subfolder, for example to differentiate like this, which would actually reflect a lot of people's structure, I think?

```yaml
BC-subfolder-note: down
BC-folder-note: same
```

**Comment by WychWitch** [comment]
Ah yes, while this is very good and I can work with it, I agree with @chrisgrieser in that My folder set up isn't meshing perfectly with this

This is how my folder structure is set up

`10 - Ash In The Snow ➜ 15 - Lore ➜ 15.02 - Theology ➜ The Different Types of Gods`

Each folder with a preceding number is a folder with a folder note (of the same name), and the last one is the note itself!

What I would love is there to be a setting so subfolders with folder notes can be automatically assigned a child (or whatever kind of relationship you want) of the enclosing foldernote, without necessarily touching the non-folder notes within it.

Because right now, if I click on the file `The Different Types of Gods`, it will have a single link to `10 - Ash In The Snow`, rather going up through the other two folder notes as expected

I hope this makes sense! If this is actually a configuration issue on my part, I'm sorry for wasting anyone's time hahaha

**Comment by zhelding** [comment]
Agreed with @WychWitch and @chrisgrieser that a "nesting" type option for sub-folders and their folder notes would be useful. 

Essentially: my folders and sub-folders are already set up in a parent-child hierarchy nested multiple levels. It would be great to have that hierarchy reflected in Breadcrumbs.

**Comment by SkepticMystic** [comment]
Ok, I'm gonna work on this now.
The requirement for the nested-folder-note is that each subfolder along the way **has to** have a corresponding note with the exact same name as the folder

**Comment by SkepticMystic** [comment]
@chrisgrieser is this issue resolved with the addition of `BC-folder-note-subfolder`?

**Comment by chrisgrieser** [comment]
yeah, from my end, you can check this off :)
(not gonna close this myself, since others might have a different opinion, but I doubt it)

**Comment by zhelding** [comment]
This is resolved in my opinion as well; thanks so much!

**Comment by WychWitch** [comment]
Me too!! hank you so much, its so seamless ^^
