### ISSUE TITLE
visual bug with hidding realtion types

### ISSUE THREAD

**Issue by tami5** [SkepticMystic/breadcrumbs#28]
Why toggling off relationship type, 
![Screen Shot 2021-06-26 at 10 08 19 PM](https://user-images.githubusercontent.com/65782666/123523226-05444f00-d6cb-11eb-99a9-2677d950c40b.png)

![Screen Shot 2021-06-26 at 10 08 26 PM](https://user-images.githubusercontent.com/65782666/123523229-09706c80-d6cb-11eb-81c2-3fcd2aae8657.png)

It would be nice if we have the ordering right and not have space between real and implied relation type

**Comment by SkepticMystic** [comment]
Thanks for posting all the issues 🙂 
With this, I'm stuck between calling it a feature request or a bug... I'm tending towards bug though. Maybe there can be a different way of distinguishing between real and implied links. Maybe the colour of the number? Maybe an emoji infront of implied links?

**Comment by tami5** [comment]
Yes different color, lighter color or emoji font might be a great solution.

**Comment by SkepticMystic** [comment]
I've fixed the numbering issue. The implied links numbering should follow on from the real links. 
There will still be a space between the two lists (because they're seperate ordered lists). You could change this by adjusting the spacing of the ordered list nested under the `div.breadcrumbs-matrix-square` element. `div.breadcrumbs-matrix-square ol { padding: 0px; margin: 0px; }`
On that note, I've added some more css classes. So you can also target `li.breadcrumbs-implied` to style implied links
