### ISSUE TITLE
Bug: dataview notes: "[[]] is not a valid dataview from-query"

### ISSUE THREAD

**Issue by LoneFireBlossom** [SkepticMystic/breadcrumbs#346]
**Describe the bug**
In dataview help, it says "you can use [[]] to reference the current file." (https://blacksmithgu.github.io/obsidian-dataview/query/sources/)
It works in dataview codeblock.
But breadcrumb doesn't support it:
```
---
BC-dataview-note: '[[]]'
BC-dataview-note-field: down
---
```
<img width="306" alt="image" src="https://user-images.githubusercontent.com/50087596/154472954-a246042f-2cdd-431d-82d7-ece966b0b834.png">

**Expected behavior**
I want to use "[[]]" to reference the current file. Because link in the frontmatter can't update automatically, so I don't want to write [[current_filename]] in the frontmatter.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.3 Beta (21E5212f)
 - Obsidian Version 0.13.23
 - dataview and breadcrumbs is up-to-date currently.

**Additional context**
I don't know if it's a feature request or a bug. 🥲

**Comment by SkepticMystic** [comment]
Hey @LoneFireBlossom, thanks for the detailed issue!
I get what you're saying. I had a look at how BC implements it, and I just pass the query right into the DV API. 

![image](https://user-images.githubusercontent.com/70717676/163716870-d2fbba24-6d2e-454b-966b-1e85f60636aa.png)

So if it throws an error, that's an issue from Dataview's side.

If you run the query in the console, you'll see an error:
![image](https://user-images.githubusercontent.com/70717676/163716856-d5766e6b-876d-4a31-b17c-d1708b65185c.png)

I'm gonna close this issue because there's nothing I can do, but I recommend adding an issue to the DV repo (or seeing if one already exists)
