### ISSUE TITLE
Bug: a note cannot be linked to another note by multiple hierarchies

### ISSUE THREAD

**Issue by justpeanuts** [SkepticMystic/breadcrumbs#353]
**Describe the bug**
If in a note named "noteA" the following is written:
up1 :: [[noteB]]
up2 :: [[noteB]]
where up1 and up2 belong to two different hierarchies.
Then, **only one of** the relations  "noteB is up1 of noteA" OR "noteB is up2 of noteA" shows up in the matrix view.

**To Reproduce**

Install the dataview plugin in addition to the breadcrumbs plugin in order to use the inline dataview syntax
1. Create a hierarchy with up direction named as "up1" 
2. Create another hierarchy with up direction named as "up2" 
3. Create a note named "noteA"
4. Create another note named "noteB"
5. Type the following text as the content of noteA:
    up1 :: [[noteB]]
    up2 :: [[noteB]]
4. Select the matrix view of the breadcrumbs plugin in the sidebar on the right hand side
5. Refresh the matrix view
6. Only either up1 or up2 is shown.

**Expected behavior**
Both up1 and up2 must be shown

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Breadcrumbs Version 2.55.2
 - obsidian version v0.13.14

**Additional context**

**Comment by ooker777** [comment]
It has a similar bug #324. Try turn it off and on to see if it works?

**Comment by justpeanuts** [comment]
> It has a similar bug #336 . Try turn it off and on to see if it works?
No, i don't think turning off and on the plugin resolves the issue.. i think the plugin is designed to not allow a single note to be related to a given note by multiple hierarchies. If so, I don't understand why this is the case.

**Comment by jeremyparadie** [comment]
I am getting the same unintuitive behavior.

It seems that two notes can only have one relationship type. This is even the case with a single hierarchy, such as two notes having both the same/sibling relation and the next/prev relation. Only one of these relations will be recognized, not both.

Here is a vault showcasing the problem: [Breadcrumbs bug demo.zip](https://github.com/SkepticMystic/breadcrumbs/files/8240513/Breadcrumbs.bug.demo.zip)

Since all of the siblings have the same parents, Sam and Martha should also be listed as Siblings.

![image](https://user-images.githubusercontent.com/14352758/158077501-036b912f-4937-432a-aa31-a5bb844d5e87.png)

Ideally, I'd like the option for next/previous relationships to also imply siblings/same relationships (and ideally only for specific hierarchy schemes)

I tried using two different up/parent down/child hierarchy schemes instead, and it seems that two notes can only have one relationship type, regardless of if the two relations are from the same hierarchy scheme or a different hierarchy scheme.

**Comment by pdworkman** [comment]
I have similar issues.

Case 1:

I have set up parent relationships in my planner, so that I get a nice YYYY > MMM > W > D breadcrumb trail. That's all good.

Days, though, don't show previous/next I guess, unless you set them up specifically.

I tried enabling the Date Notes Alternative Hierarchy, but I don't get Next/Previous anywhere. Is this because I am using Periodic Notes rather than Daily Notes? Or because I'm already using a primary hierarchy and can't also use an Alternative Hierarchy? Or something else I haven't thought of?

Case 2:

Using only one hierarchy, I find that I cannot use parent/sibling/child and next/previous in the same note. I can use next/previous alone, but as soon as I add parent/sibling/child, the next/previous is ignored, and it only uses parent/sibling/child.

**Comment by SkepticMystic** [comment]
Thanks for the info, everyone. I agree that a note should be able to show up in multiple hierarchies. I'll have to see why this isn't being allowed currently

**Comment by JeremyParadie** [comment]
Any updates? 
Or suggestions for how I could fix this myself in the breadcrumbs code? I don't have experience with Obsidian plugin development yet.

**Comment by SkepticMystic** [comment]
No updates. I'm not really able to work on this project much these days. Perhaps during my time off work I can take a look

**Comment by SkepticMystic** [comment]
@JeremyParadie @justpeanuts please consider upgrading to v4, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
This issue is resolved in the beta
