### ISSUE TITLE
Long Term Feature request: use SKOS?

### ISSUE THREAD

**Issue by brimwats1** [SkepticMystic/breadcrumbs#4]
The most comprehensive organization system for digital materiel is SKOS: https://www.w3.org/TR/skos-reference/

here are the subcategories to SKOS —its probably not necessary to use all of these. TopConcept, prefLabel definition, broader, narrower, related and then the broad/close/exact/related/etc Matches would satisfy 70% of uses

| skos:Concept            	|
|-------------------------	|
| skos:ConceptScheme      	|
| skos:inScheme           	|
| skos:hasTopConcept      	|
| skos:topConceptOf       	|
| skos:altLabel           	|
| skos:hiddenLabel        	|
| skos:prefLabel          	|
| skos:notation           	|
| skos:changeNote         	|
| skos:definition         	|
| skos:editorialNote      	|
| skos:example            	|
| skos:historyNote        	|
| skos:note               	|
| skos:scopeNote          	|
| skos:broader            	|
| skos:broaderTransitive  	|
| skos:narrower           	|
| skos:narrowerTransitive 	|
| skos:related            	|
| skos:semanticRelation   	|
| skos:Collection         	|
| skos:OrderedCollection  	|
| skos:member             	|
| skos:memberList         	|
| skos:broadMatch         	|
| skos:closeMatch         	|
| skos:exactMatch         	|
| skos:mappingRelation    	|
| skos:narrowMatch        	|
| skos:relatedMatch       	|

**Comment by SkepticMystic** [comment]
Would it be enough to allow arbitrarily many field names? So instead of only allowing one parent, sibling, and child field name, you could use as many as you want?
Something like: `Parent Field Names: parent, broader, collection`, for example?

**Comment by weeyizhi** [comment]
At the moment, this plugin provides a view of the hierarchy of notes created by the user. How it current does it is by having an undirected graph, with the root of the graph (usually called the index) as the top of the graph. Everything beneath the root is a descendant. And therefore the graph is in itself is just a parent-child relationship graph. With this graph, one can get to know siblings, parents, children, or any descendant/ancestor. That makes it possible for the breadcrumbs/trail view that shows the path from the root to the current file. Or to show other relationships like parents, siblings, etc.

But to support SKOS, an undirected graph would no longer suffice, as multiple relationships are possible (all the ones listed in the first post). It seems to me that the [juggl plugin](https://juggl.io/Juggl) is more suitable for such purpose. Since juggl supports the creation of any"types" of links, one can easily create those SKOS relationships in juggl, and see those relationship in the graph view. The Neo4j bloom graph visualization method mentioned [here](https://juggl.io/Neo4j+Graph+View/Neo4j+graph+visualizations) seems to be a good way of visualization SKOS.

Juggl can also be used with this plugin so that you can get breadcrumbs or matrix view of siblings, parents, children, etc.

**Comment by brimwats** [comment]
@weeyizhi a plugin that will be coming soon (that I can't comment on otherwise) will enable and easily allow the addition of SKOS items to notes. These will be readable from YAML and can be matched to dataview fields. Juggl is fantastic but is meant for the individual annotation of notes without the use of controlled vocabularies.

**Comment by SkepticMystic** [comment]
The current setup does indeed use directed graphs. Based on the explicit parent, sibling, and child fields in one's notes, 3 different graphs are constructed; one for each type of field.
These graphs give enough info to show the regular, explicit matrix, but now you can also see _implied_ parents, siblings, and children as of `0.2.1`

**Comment by SkepticMystic** [comment]
@brimwats can I get your thoughts on this issue in the context of all the new features, especially multiple hierarchies.
Is this more achievable now that it used to be? Are there things Breadcrumbs still can't do that this FR is asking for?
It seems like some of the fields it proposes are fundamentally different from a simple `up`, `same`, or `down` relation. Stuff like `TopConcept` would be like a marker for the top of a hierarchy, for example

**Comment by brimwats** [comment]
> It seems like some of the fields it proposes are fundamentally different from a simple up, same, or down relation. Stuff like TopConcept would be like a marker for the top of a hierarchy, for exampl

that's exactly right! which means it would be longer term, and perhaps something out of scope for you right now! feel free to close if so :)

**Comment by SkepticMystic** [comment]
@brimwats1 hey :)
I'm not sure if you've seen, I've recently rewritten Breadcrumbs from scratch, more info here: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md

Given this, I think the following features are enough to achieve _alot_ of the desired results. Most of these were not possible when this issue was created:

- Multiple, separate hierarchies
- Implied relations are toggleable, on a hierarchy-level
- Fully custom implied relations, super powerful feature! You can create implied relations using fields from _multiple_ hierarchies

Specifically the last point, you can create very customised relationships, not possible before. Have a look at the section new README and let me know your thoughts: https://github.com/SkepticMystic/breadcrumbs/tree/master#custom-transitive-relations

**Comment by SkepticMystic** [comment]
Cool cool :)
