### ISSUE TITLE
FR: Support for Markdown Style Links (non-Wikilinks)

### ISSUE THREAD

**Issue by smaroukis** [SkepticMystic/breadcrumbs#454]
**Is your feature request related to a problem? Please describe.**
I switched over to using markdown-style links (as opposed to wikilinks) to increase cross-platform compatibility, but it doesn't seem like Breadcrumbs supports this link style.  

I'm also creating this FR to document this missing-functionality, since it seems most people use the wikilink style within Obsidian and this might be a one-off request.

With Wikilink formatting, the hierarchy appears correctly:
<img width="1582" alt="wikilink-example" src="https://user-images.githubusercontent.com/9443032/199143113-b5afc5d2-b4b3-4726-bf18-3f4b8caee9a1.png">

With regular Markdown link formatting, the hierarchy does not appear:
<img width="1582" alt="markdown-link-example" src="https://user-images.githubusercontent.com/9443032/199143147-dc316eb1-a8cc-4ecf-96fc-19b2e731d22a.png">

**Comment by trevorhook** [comment]
this FR has my vote.

Breadcrumbs looks like a great plugin but it fails to identify my links because I'm using markdown style links. I'm going to carrying on tagging notes with "Previous" markdown links in the hope this feature request gets implemented at somepoint in the future.

Note: I'm using Dendron naming convention so Up/Down/Same can be automtically identified, it is just the next/prev that breadcrumbs is unable to identify at the moment.

**Comment by nbossard** [comment]
Same issue for me, plugin does not support markdown links

**Comment by SkepticMystic** [comment]
Do you know if the Obsidian API detects and exposes these somewhere? If not, I don't think it's worth it for me to parse the note content, which is far more intensive

**Comment by SkepticMystic** [comment]
Note for my own reference, this isn't as intense as I initially thought. I still need to parse the markdown links, but Dataview and Obsidian both expose the raw string as metadata fields

**Comment by SkepticMystic** [comment]
Happy to say this is now possible!
If you use the V4 beta, and have Dataview enabled, then Breadcrumbs will detect markdown links of the form `field:: [display](folder/path.md)`
