### ISSUE TITLE
Bug: v4, codeblocks generate list in reverse order

### ISSUE THREAD

**Issue by soulsynapse** [SkepticMystic/breadcrumbs#507]
**Describe the bug**
The list is in reverse order 

**To Reproduce**
1. Make a codeblock list
2. It's in reverse order by default

**Expected behavior**
It should be in alphabetical order descending, not ascending

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version 4
**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by soulsynapse** [comment]
i pushed a fix

**Comment by SkepticMystic** [comment]
Hey there, thanks for the issue!
I think what's happening is that by default, the items are sorted _in the order they're added to the Breadcrumbs graph_, not in alphabetical order of filename. 

To achieve that, you can use `sort: basename asc`. I'll make it so that you can just use `sort: basename`, and `asc` will be implied as the default.

Please let me know if that addresses this issue

**Comment by soulsynapse** [comment]
Maybe, but also the default sort order is 1, not -1. I highlighted the change in my pull request which fixes the problem for codeblocks.

**Comment by soulsynapse** [comment]
Yes sort: basename asc fixes the issue.

**Comment by SkepticMystic** [comment]
Alright, I'm gonna close this out.
As I said, I'll make `asc` implied, so you don't have to add it.
Also, arguablly `basename` should be the default sort field, instead of the graph order. So I may change that as well
