### ISSUE TITLE
Calculate graphs once, with a button to refresh

### ISSUE THREAD

**Issue by SkepticMystic** [SkepticMystic/breadcrumbs#53]
Running the entire computation every time `active-leaf-change` fires is getting expensive.
I can `initGraphs` once `onload`, and then have a button to refresh them as desired.
The auto refresh interval can also refresh the graphs.

**Comment by BricoleurSoul** [comment]
I wondered about that and was thinking of lengthening the refresh time period but had yet tried to see if that caused problems on initial load.

**Comment by SkepticMystic** [comment]
Do you experience noticeable lag when changing notes?
I've been surprised at how fast things are, even on larger vaults. But with the new features being added things are understandably starting to slow down

**Comment by BricoleurSoul** [comment]
I haven't noticed anything worrisome yet  but only have about 2,500 notes so far.

**Comment by SkepticMystic** [comment]
Alright, maybe this isn't such a big issue. I can also make it optional, so that if someone wants to, the whole computation can be run everytime

**Comment by BricoleurSoul** [comment]
I am getting heat issues on my Mac Laptop recently - I not sure the root cause yet but it does seem to be somewhere in Obsidian - but I've been beating the heck out of the poor machine with incessant runs of data view  as well as  building new breadcrumb chains through my vault.  I am going to increase refresh time on Breadcrumbs to see if that has impact - if not then I will guess that 2 data view entries I currently have at the bottom of virtually every page [set by new note template(s)] is the culprit and I will have to live with it until I finish building extensive(enough)  real breadcrumb chains. :)

**Comment by SkepticMystic** [comment]
Implemented in recent 0.10.... release
