### ISSUE TITLE
Feature Request: automated renaming of parents/children in notes

### ISSUE THREAD

**Issue by stefanopagliari** [SkepticMystic/breadcrumbs#80]
Currently Obsidian automatically renames the links to a note when this is renamed. I do not know if this is possible with a simple plugin, but it would be helpful if breadcrumbs could do the same, updating the references to a parent/child note when this is renamed.

Just an idea/suggestion, not something that is pressing.

**Comment by SkepticMystic** [comment]
Hey Stefano :)

So if you have a link in the content of your note, it will automatically be renamed when changing the name of the note it links to.
But if the link is in the YAML of the note, then it doesn't get renamed. Is that what you're referring to?
If so, that is because Obsidian doesn't see `[[wikilinks]]` in yaml as real links, I've just written Breadcrumbs to work around this. And so, there wouldn't be an easy way to make the yaml update when the note name is changed, aside from manually implementing such a feature (which makes me worry that I accidentally overwrite something in the file).
For now, using dataview inline fields will give you the renaming functionality.
Putting an inline field in the content of the note (not the yaml), means that Obsidian will automatically update it when the note is renamed. 

`parent:: [[Note]]`

**Comment by SkepticMystic** [comment]
@stefanopagliari what do you think?
I agree that it would be useful for the yaml to be updated when a note is renamed, but I think that would be a whole plugin on its own. As I'm sure many people would find that useful while also not wanting Breadcrumbs installed.

**Comment by konhi** [comment]
In my opinion it's indeed very useful and wanted feature, and it's good if it would be separate plugin!

**Comment by SkepticMystic** [comment]
Cool cool, I'm gonna close this issue out then. This feature should be it's own plugin :)
